### ISSUE TITLE
La date des posts s'affiche en Anglais

### ISSUE THREAD

**Issue by viroulep** [speedcubingfrance/speedcubingfrance.org#1]

**Comment by zeecho** [comment]
Un lien qui explique les différents types de formattage : http://alanwsmith.com/jekyll-liquid-date-formatting-examples
Un post qui explique comment créer un module pour traduire la date : https://stackoverflow.com/a/32331857

Je ferai ça quand j'aurai un peu de temps, ça doit pas être long
