### ISSUE TITLE
Amélioration de la sécurité SSH

### ISSUE THREAD

**Issue by d4rklynk** [speedcubingfrance/speedcubingfrance.org#206]
### Problème :
Un mot de passe m'est demandé lors de la connexion SSH au serveur de l'AFS. Il ne devrait demander qu'une clé SSH.

### Comportement attendu :
Une clé SSH devrait être créé pour chaque utilisateur de la team, et les mots de passe bloqués dans la configuration.

Un enregistrement DNS de type SSHFP devrait également être inclu. Cela permettrait d'éviter le TOFU (Trust-On-First-Use).

**Comment by viroulep** [comment]
Corrigé [ici](https://github.com/speedcubingfrance/speedcubingfrance.org/blob/master/ci/chef/cookbooks/afs/templates/sshd_afs.conf).

En pratique je n'ai pas corrigé ça plus tôt parce que c'était un "faux" problème : tous les utilisateurs du site étaient "locked" et du coup aucun ne pouvait se connecter avec un mot de passe de toute manière :)
Merci d'avoir rapporté le problème !
