### ISSUE TITLE
menu déroulant trop bas

### ISSUE THREAD

**Issue by spols** [speedcubingfrance/speedcubingfrance.org#23]
J'utilise google chrome Version 64.0.3282

sur les 2 menus déroulants Association et Speedcubing.   si je ne vais pas assez vite entre le bouton et le menu le menu se referme car il il y une petite zone vide de 3px entre le bouton et le menu.

**Comment by zeecho** [comment]
Exact. 
FIx à faire : il suffit de mettre un top:95% au lieu de 100% sur .dropdown-menu

**Comment by spols** [comment]
En fait il serait plus logique de réduire la margin-top de .dropdown-menu

ou d'exprimer le top en px voir même un calcul calc(100% - 2px)
