### ISSUE TITLE
Section spécifique pour les liens sur le site

### ISSUE THREAD

**Issue by viroulep** [speedcubingfrance/speedcubingfrance.org#3]
On voudrait afficher des liens vers des sites persos, mais ça va vite surcharger la page d'accueil.
Du coup il faudrait créer une page à part sur laquelle on pourrait mettre des liens/une petite description.

@zeecho, ça te dirait pas d'essayer de faire ça ?
On doit pouvoir s'en sortir simplement avec un page markdown et du copié collé, mais la version propre ça serait un yaml ou json avec tous les liens/descriptions/miniatures, sur lequel on itère dans une page à part (directement via jekyll, pas en js).

**Comment by zeecho** [comment]
Ouai, si j'oublie pas, je dois pouvoir m'en charger ! (surtout que j'avais déjà testé un peu Jekyll donc je vois globalement comment ça marche).

**Comment by zeecho** [comment]
À priori c'est cette page : https://www.speedcubingfrance.org/ressources
L'histoire de jekyll n'est bien sûr plus d'actualité mais je suppose que le but est tout de même de toujours passer par du yaml ou du json. J'essaierai de regarder si je suis inspiré. En attendant, si des gens peuvent commencer une compil de liens, ça peut être cool

**Comment by viroulep** [comment]
Implémenté dans #42
