### ISSUE TITLE
Envoyer des notifications de compétitions aux membres ?

### ISSUE THREAD

**Issue by zeecho** [speedcubingfrance/speedcubingfrance.org#31]
Je crois que c'est Jules qui avait commencé à parler de ça. En gros, un des intérêts d'être membre pourrait être de recevoir une notification quand une compet en France est annoncée sur la WCA et/ou une notif quand les inscriptions d'une compet en France ouvrent. Ce serait un petit pluss sympa qui pourraient peut-être aussi inciter encore un peu pluss de gens à adhérer

Tu en penses quoi @viroulep ?

**Comment by viroulep** [comment]
En gros lorsqu'on récupère une nouvelle compétition via la WCA on enverrai une notification aux adhérents qui ont leur notification `on` ?
Ou à tous les utilisateurs du site ?

**Comment by zeecho** [comment]
C'est ça. Et oui, l'un ou l'autre. C'est probablement mieux de le faire que pour les gens qui ont leurs notifs activées, effectivement

**Comment by MrChamo** [comment]
Oui, très bonne idée et le fait de le faire que pour les gens qui ont les notifs on permet d'éviter les désagréments pour les personnes qui s'en foutent.
(ouais, j'en ai profité pour créer un compte là)

**Comment by HippolyteM** [comment]
Tiens mais pourquoi j'étais pas abonné au github afs moi???:/

C'est une idée top!
Pour à qui l'envoyer, c'est sûr que l'opt-out c'est pas ouf si on peut l'éviter. En même temps il faudra bien communiquer sur le truc pour que les gens activent leur notifs ou non en connaissance de cause.

J'allais aussi suggérer un mail à x places restantes, mais outre la surcharge de mails, j'ai peur que ça ait aussi l'effet pervers de blinder les dernières inscriptions avec des gens pas du tout sûr de venir mais affolés par le mail.

Également, Jules avait parlé de mail quand les comp étaient en discussion, mais c'est un peu subjectif comme critère. A partir de quand une comp est assez "en discussion", assez probable pour qu'on mail à ce sujet? Vu qu'il y a toujours un délai pour les inscriptions, peut-être que l'officialisation peut suffire.

**Comment by zeecho** [comment]
@viroulep FYI c'est celle-ci l'issue dont on parlait en AG qui apporterait un bon petit plus au fait d'être adhérent ;)
