### ISSUE TITLE
Problème affichage checkbox sur page competitions

### ISSUE THREAD

**Issue by zeecho** [speedcubingfrance/speedcubingfrance.org#35]
Je pense que la capture d'écran parle d'elle même. C'est peut-être lié à la [màj de bootstrap](https://github.com/speedcubingfrance/speedcubingfrance.org/pull/34/commits/5449e50cd04f325d10bec579aff084e3002e2a17) ? 

![2018-10-08-132952_504x419_scrot](https://user-images.githubusercontent.com/5508488/46606684-72b88780-cafe-11e8-9cf0-fa97585d7225.png)

**Comment by viroulep** [comment]
Ouais c'est clairement ça, je regarde ce soir.
