### ISSUE TITLE
Liste de discussions adhérents

### ISSUE THREAD

**Issue by viroulep** [speedcubingfrance/speedcubingfrance.org#61]
Le groupe existe dans gsuite.

Il faudrait : 
  - ajouter un booléen dans la table user "je veux être ajouté dans la liste de discussions adhérents)
  - ajuster le job de synchronisation pour récupérer les utilisateurs adhérents qui ont ça d'activer, et synchroniser le groupe

**Comment by zeecho** [comment]
Je comptais essayer de lancer une newsletter aussi. Je ne sais pas s'il vaut mieux l'envoyer sur discussions ou créer encore une autre ML avec opt-in explicite des gens
